# Generated by Django 6.0.6 on 2026-06-24 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_commande_stock_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cuisinier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
