# Generated by Django 6.0.6 on 2026-06-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AddField(
            model_name='profile',
            name='siret',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='siret_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
