# Generated by Django 6.0.6 on 2026-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_avis_options_profile_siret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
