# Generated by Django 6.0.6 on 2026-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_profile_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
