# Generated by Django 6.0.6 on 2026-06-29 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_profile_siret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('cuisinier', 'Cuisinier'), ('livreur', 'Livreur')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(choices=[('velo', 'Vélo'), ('scooter', 'Scooter'), ('voiture', 'Voiture'), ('pieds', 'À pied')], default='velo', max_length=20)),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('disponible', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
